[package]
name = "test_scheduler"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at="0x25c3b9751885c81c8ced7356b7aa6fad4a3a837c1d92926667dc0b47aa2b4876"
authors=["jarjar.xyz"]
# license = ""           # e.g., "MIT", "GPL", "Apache 2.0"
# authors = ["..."]      # e.g., ["Joe Smith (joesmith@noemail.com)", "John Snow (johnsnow@noemail.com)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }
jarjar_scheduler = { git = "https://github.com/jarjar-xyz/jarjar_scheduler.git", subdir = "contracts/jarjar_scheduler", rev = "main" }
binks = { git = "https://github.com/jarjar-xyz/binks", subdir = "", rev = "main" }

[addresses]
binks="0xc288caf405af52affcff65150c81e1c584453c0c13cbf3a938f51282a37e7031"
jarjar_scheduler="0x1295ff206bb3110949b2eead14a93792ced095184828e374aa00a70e7906e24b"
test_scheduler = "0x0"

[dev-dependencies]

# The dev-dependencies section allows overriding dependencies for `--test` and
# `--dev` modes. You can introduce test-only dependencies here.
# Local = { local = "../path/to/dev-build" }

[dev-addresses]
# The dev-addresses section allows overwriting named addresses for the `--test`
# and `--dev` modes.
# alice = "0xB0B"

